# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 247d4f513319da6c9908ae0528f5da87ab0b141fc95f8a80fb394b2c42108d77134883834aada1563f346e07bdca0ad8f617a881197c5ab91ab04bd3d3459d83

test:
  secret_key_base: 0effd74b1ad14c01b5e972a58ab7ecca866c18d6d3eafc4a03b81fb3e1d5a5d99f9b3ce450c373d44da712b6599d56675fdf230bee89ff1afe786544dc4424ba

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
